name: Rust Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [server, client] # Specify each project directory

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # Use the stable Rust toolchain

    - name: Build ${{ matrix.project }}
      run: cargo build --verbose
      working-directory: ./${{ matrix.project }}

    - name: Test ${{ matrix.project }}
      run: cargo test --verbose
      working-directory: ./${{ matrix.project }}

